charm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from charm.apps import CharmConfig
from charm.views import FlukeCreateView, CharmCreateView, CharmListView, CharmDetailView, CharmUpdateView, \
    CharmDeleteView, FlukeListView, FlukeUpdateView, FlukeDeleteView, error_connection, ConnectionCreateView, \
    verification

app_name = CharmConfig.name

urlpatterns = [
    path('fluke_create/', FlukeCreateView.as_view(), name='fluke_create'),
    path('fluke_list/', FlukeListView.as_view(), name='fluke_list'),
    path('fluke_update/<int:pk>', FlukeUpdateView.as_view(), name='fluke_update'),
    path('fluke_delete/<int:pk>', FlukeDeleteView.as_view(), name='fluke_delete'),
    path('', CharmListView.as_view(), name='charm_list'),
    path('charm_create/', CharmCreateView.as_view(), name='charm_create'),
    path('charm_detail/<int:pk>', CharmDetailView.as_view(), name='charm_detail'),
    path('charm_update/<int:pk>', CharmUpdateView.as_view(), name='charm_update'),
    path('charm_delete/<int:pk>', CharmDeleteView.as_view(), name='charm_delete'),
    path('connection_create/', ConnectionCreateView.as_view(), name='connection_create'),
    path('error_connection/', error_connection, name='error_connection'),
        path('verification/', verification, name='verification'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('charm.urls', namespace='charm')),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, UserLoginView

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

charm/models.py
from django.db import models

from users.models import NULLABLE, NOT_NULLABLE


class Fluke(models.Model):
    serial_number = models.CharField(max_length=100, verbose_name='S/N', unique=True, **NOT_NULLABLE)
    IP = models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP', **NOT_NULLABLE, help_text='IP адрес устройства')

    def __str__(self):
        return f'{self.serial_number}'

    class Meta:
        verbose_name = 'Эталон'
        verbose_name_plural = 'Эталоны'


class Charm(models.Model):
    serial_number = models.CharField(max_length=100, verbose_name='S/N', unique=True, **NOT_NULLABLE)

    def __str__(self):
        return f'{self.serial_number}'

    class Meta:
        verbose_name = 'Чарм'
        verbose_name_plural = 'Чармы'


class Muster(models.Model):
    measurement = models.DecimalField(max_digits=6, decimal_places=0, **NULLABLE, verbose_name='Результат измерения')
    verifier = models.ForeignKey('users.User', on_delete=models.SET_NULL, **NULLABLE, verbose_name='Поверитель')
    fluke = models.ForeignKey('charm.Fluke', on_delete=models.SET_NULL, **NULLABLE, verbose_name='Fluke')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата измерения', **NULLABLE)
    charm = models.ForeignKey('charm.Charm', on_delete=models.SET_NULL, **NULLABLE, verbose_name='Чарм')

    def __str__(self):
        return f'{self.charm}'

    class Meta:
        verbose_name = 'Поверка'
        verbose_name_plural = 'Поверка'

charm/forms.py
from django import forms

from charm.models import Charm, Fluke, Muster


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():

            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'


class FlukeForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Fluke
        fields = ('serial_number', 'IP')


class CharmForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Charm
        fields = ('serial_number',)


# class MusterCreateForm(StyleFormMixin, forms.ModelForm):
#     class Meta:
#         model = Muster
#         fields = ('charm', 'fluke')


# class MeasurementCreateForm(StyleFormMixin, forms.ModelForm):
#     class Meta:
#         model = Muster
#         fields = ('fluke', 'measurement')
#
#     def __init__(self, *args, **kwargs):
#         super(MeasurementCreateForm, self).__init__(*args, **kwargs)
#         instance = getattr(self, 'instance', None)
#         if instance and instance.pk:
#             self.fields['fluke'].widget.attrs['readonly'] = True


class ConnectionCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Muster
        fields = ('fluke',)

charm/views.py
from unittest.mock import NonCallableMock

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from hvl_ccb.comm.telnet import TelnetError
from hvl_ccb.dev.fluke884x import MeasurementFunction

from charm.forms import FlukeForm, CharmForm, ConnectionCreateForm
from charm.models import Charm, Fluke, Muster
from charm.services import connection

from config import settings


class ConnectionCreateView(LoginRequiredMixin, CreateView):
    model = Muster
    form_class = ConnectionCreateForm
    template_name = 'charm/connection_form.html'
    success_url = reverse_lazy('charm:charm_list')

    def form_valid(self, form):
        muster = form.save(commit=False)
        fluke = muster.fluke
        try:
            dev = connection(str(fluke.IP))
            settings.CONNECT = dev
            settings.CONNECT.measurement_function = MeasurementFunction.VOLTAGE_DC
        except TelnetError:
            return redirect('charm:error_connection')
        return super().form_valid(form)


def error_connection(request):
    return render(request, 'charm/error.html')


def verification(request):
    if request.method == 'POST':
        if request.POST.get('next') is not None:
            if settings.CONNECT is None:
                return redirect('charm:error_connection')
            else:
                measurement = settings.CONNECT.measure()*1000
                print(measurement)
        elif request.POST.get('stop') is not None:
            settings.CONNECT.stop()
            settings.CONNECT = None
            return redirect('charm:charm_list')
    return render(request, 'charm/verification.html')


class FlukeCreateView(CreateView):
    model = Fluke
    form_class = FlukeForm
    success_url = reverse_lazy('charm:fluke_list')


class FlukeListView(LoginRequiredMixin, ListView):
    model = Fluke


class FlukeUpdateView(UpdateView):
    model = Fluke
    form_class = FlukeForm
    success_url = reverse_lazy('charm:fluke_list')


class FlukeDeleteView(DeleteView):
    model = Fluke
    success_url = reverse_lazy('charm:fluke_list')


class CharmCreateView(CreateView):
    model = Charm
    form_class = CharmForm
    success_url = reverse_lazy('charm:charm_list')


class CharmListView(LoginRequiredMixin, ListView):
    model = Charm


class CharmDetailView(LoginRequiredMixin, DetailView):
    model = Charm


class CharmUpdateView(UpdateView):
    model = Charm
    form_class = CharmForm
    success_url = reverse_lazy('charm:charm_update')


class CharmDeleteView(DeleteView):
    model = Charm
    success_url = reverse_lazy('charm:charm_list')

charm/templates/charm/includes/inc_footer.html
{% load static %}
<footer class="text-muted py-5">
    <div class="container">
        <p class="mb-1">Hi!</p>
        <p class="mb-0"><a href="{% url 'charm:charm_list' %}">Главная</a></p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

charm/templates/charm/includes/inc_main_menu.html
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'charm:charm_list' %}"> Поверка </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'charm:fluke_list' %}"> Эталоны </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'charm:connection_create' %}"> Подключиться к эталону </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'charm:fluke_create' %}"> Добавить эталон </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'users:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'users:register' %}">Зарегестироваться</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>