charm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from charm.apps import CharmConfig
from charm.views import FlukeCreateView, CharmCreateView, CharmListView, CharmDetailView, CharmUpdateView, \
    CharmDeleteView, FlukeListView, FlukeUpdateView, FlukeDeleteView, error_connection, ConnectionCreateView, \
    verification

app_name = CharmConfig.name

urlpatterns = [
    path('fluke_create/', FlukeCreateView.as_view(), name='fluke_create'),
    path('fluke_list/', FlukeListView.as_view(), name='fluke_list'),
    path('fluke_update/<int:pk>', FlukeUpdateView.as_view(), name='fluke_update'),
    path('fluke_delete/<int:pk>', FlukeDeleteView.as_view(), name='fluke_delete'),
    path('', CharmListView.as_view(), name='charm_list'),
    path('charm_create/', CharmCreateView.as_view(), name='charm_create'),
    path('charm_detail/<int:pk>', CharmDetailView.as_view(), name='charm_detail'),
    path('charm_update/<int:pk>', CharmUpdateView.as_view(), name='charm_update'),
    path('charm_delete/<int:pk>', CharmDeleteView.as_view(), name='charm_delete'),
    path('connection_create/', ConnectionCreateView.as_view(), name='connection_create'),
    path('error_connection/', error_connection, name='error_connection'),
        path('verification/', verification, name='verification'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('charm.urls', namespace='charm')),
]

charm/models.py
from django.db import models

from users.models import NULLABLE, NOT_NULLABLE


class Fluke(models.Model):
    serial_number = models.CharField(max_length=100, verbose_name='S/N', unique=True, **NOT_NULLABLE)
    IP = models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP', **NOT_NULLABLE, help_text='IP адрес устройства')

    def __str__(self):
        return f'{self.serial_number}'

    class Meta:
        verbose_name = 'Эталон'
        verbose_name_plural = 'Эталоны'


class Charm(models.Model):
    serial_number = models.CharField(max_length=100, verbose_name='S/N', unique=True, **NOT_NULLABLE)

    def __str__(self):
        return f'{self.serial_number}'

    class Meta:
        verbose_name = 'Чарм'
        verbose_name_plural = 'Чармы'


class Muster(models.Model):
    measurement = models.DecimalField(max_digits=6, decimal_places=0, **NULLABLE, verbose_name='Результат измерения')
    verifier = models.ForeignKey('users.User', on_delete=models.SET_NULL, **NULLABLE, verbose_name='Поверитель')
    fluke = models.ForeignKey('charm.Fluke', on_delete=models.SET_NULL, **NULLABLE, verbose_name='Fluke')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата измерения', **NULLABLE)
    charm = models.ForeignKey('charm.Charm', on_delete=models.SET_NULL, **NULLABLE, verbose_name='Чарм')

    def __str__(self):
        return f'{self.charm}'

    class Meta:
        verbose_name = 'Поверка'
        verbose_name_plural = 'Поверка'

charm/forms.py
from django import forms

from charm.models import Charm, Fluke, Muster


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():

            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'


class FlukeForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Fluke
        fields = ('serial_number', 'IP')


class CharmForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Charm
        fields = ('serial_number',)


# class MusterCreateForm(StyleFormMixin, forms.ModelForm):
#     class Meta:
#         model = Muster
#         fields = ('charm', 'fluke')


# class MeasurementCreateForm(StyleFormMixin, forms.ModelForm):
#     class Meta:
#         model = Muster
#         fields = ('fluke', 'measurement')
#
#     def __init__(self, *args, **kwargs):
#         super(MeasurementCreateForm, self).__init__(*args, **kwargs)
#         instance = getattr(self, 'instance', None)
#         if instance and instance.pk:
#             self.fields['fluke'].widget.attrs['readonly'] = True


class ConnectionCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Muster
        fields = ('fluke',)

charm/views.py
from unittest.mock import NonCallableMock

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from hvl_ccb.comm.telnet import TelnetError
from hvl_ccb.dev.fluke884x import MeasurementFunction

from charm.forms import FlukeForm, CharmForm, ConnectionCreateForm
from charm.models import Charm, Fluke, Muster
from charm.services import connection

from config import settings


class ConnectionCreateView(LoginRequiredMixin, CreateView):
    model = Muster
    form_class = ConnectionCreateForm
    template_name = 'charm/connection_form.html'
    success_url = reverse_lazy('charm:charm_list')

    def form_valid(self, form):
        muster = form.save(commit=False)
        fluke = muster.fluke
        try:
            dev = connection(str(fluke.IP))
            settings.CONNECT = dev
            settings.CONNECT.measurement_function = MeasurementFunction.VOLTAGE_DC
        except TelnetError:
            return redirect('charm:error_connection')
        return super().form_valid(form)


def error_connection(request):
    return render(request, 'charm/error.html')


def verification(request):
    if request.method == 'POST':
        if request.POST.get('next') is not None:
            if settings.CONNECT is None:
                return redirect('charm:error_connection')
            else:
                measurement = settings.CONNECT.measure()*1000
                print(measurement)
        elif request.POST.get('stop') is not None:
            settings.CONNECT.stop()
            settings.CONNECT = None
            return redirect('charm:charm_list')
    return render(request, 'charm/verification.html')


class FlukeCreateView(CreateView):
    model = Fluke
    form_class = FlukeForm
    success_url = reverse_lazy('charm:fluke_list')


class FlukeListView(LoginRequiredMixin, ListView):
    model = Fluke


class FlukeUpdateView(UpdateView):
    model = Fluke
    form_class = FlukeForm
    success_url = reverse_lazy('charm:fluke_list')


class FlukeDeleteView(DeleteView):
    model = Fluke
    success_url = reverse_lazy('charm:fluke_list')


class CharmCreateView(CreateView):
    model = Charm
    form_class = CharmForm
    success_url = reverse_lazy('charm:charm_list')


class CharmListView(LoginRequiredMixin, ListView):
    model = Charm


class CharmDetailView(LoginRequiredMixin, DetailView):
    model = Charm


class CharmUpdateView(UpdateView):
    model = Charm
    form_class = CharmForm
    success_url = reverse_lazy('charm:charm_update')


class CharmDeleteView(DeleteView):
    model = Charm
    success_url = reverse_lazy('charm:charm_list')

charm/templates/charm/base.html
<!doctype html>
{% load static %}
<html lang="ru" prefix="og: http://ogp.me/ns#">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Catalog</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-grid.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reboot.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reboot.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'charm/includes/inc_main_menu.html' %}

<main>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</main>
{% include 'charm/includes/inc_footer.html' %}

</body>
</html>

charm/templates/charm/charm_confirm_delete.html
{% extends 'charm/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <form method="post">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Хотите удалить FLuke: {{ object.serial_number }}? </h5>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger active">Удалить</button>
                        <a href="{% url 'charm:charm_list' %}" class="btn btn-success active">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

charm/templates/charm/charm_detail.html
{% extends 'charm/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ object.serial_number }}</li>
                    <li class="list-group-item">{{ object.calibrator }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

charm/templates/charm/charm_form.html
{% extends 'charm/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            {% csrf_token %}
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Сохранить" class="btn btn-success">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

charm/templates/charm/charm_list.html
{% extends 'charm/base.html' %}

{% block content %}
{% for object in object_list %}
<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <h5 class="card-title">Charm</h5>
            <p class="card-text"> Серийный номер: {{ object.serial_number }} </p>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url 'charm:charm_detail' object.pk %}" class="btn btn-primary">Детали</a>
                <a href="{% url 'charm:charm_update' object.pk %}" class="btn btn-primary">Редактировать</a>
                <a href="{% url 'charm:charm_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

charm/templates/charm/connection_form.html
{% extends 'charm/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            {% csrf_token %}
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Сохранить" class="btn btn-success">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

charm/templates/charm/error.html
{% extends 'charm/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">Ошибка подключения, перепроверьте правильность выбранного устройства и его IP адрес</h4>
        </div>
    </div>
</div>
{% endblock %}

charm/templates/charm/first_muster.html
{% extends 'charm/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ ind }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

charm/templates/charm/fluke_confirm_delete.html
{% extends 'charm/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <form method="post">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Хотите удалить FLuke: {{ object.serial_number }}? </h5>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger active">Удалить</button>
                        <a href="{% url 'charm:fluke_list' %}" class="btn btn-success active">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

charm/templates/charm/fluke_form.html
{% extends 'charm/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            {% csrf_token %}
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Сохранить" class="btn btn-success">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

charm/templates/charm/fluke_list.html
{% extends 'charm/base.html' %}

{% block content %}
{% for object in object_list %}
<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <h5 class="card-title">Fluke8846A</h5>
            <p class="card-text"> Серийный номер: {{ object.serial_number }} </p>
            <p class="card-text"> IP адрес: {{ object.IP }} </p>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url 'charm:fluke_update' object.pk %}" class="btn btn-primary">Редактировать</a>
                <a href="{% url 'charm:fluke_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

charm/templates/charm/verification.html
{% extends 'charm/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ ind }}</li>
                </ul>
            </div>
        </div>
        <div class="col-12">
            <div class="col-6">
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="start"/>
                    <button type="submit" class="btn btn-success">Success</button>
                </form>
            </div>
            <div class="col-6">
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="stop" value="stop"/>
                    <button type="submit" class="btn btn-danger">danger</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}